# Generated by Django 3.2.1 on 2023-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpcenter', '0005_auto_20230727_0234'),
        ('helpcenter', '0005_auto_20230727_1354'),
    ]

    operations = [
    ]
